# Generated by Django 6.0.6 on 2026-06-15 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPredictionLog',
            fields=[
                ('prediction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module_name', models.CharField(max_length=100)),
                ('request_source', models.CharField(default='api', max_length=100)),
                ('input_payload', models.JSONField()),
                ('output_payload', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('response_time_ms', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_identifier', models.CharField(default='system', max_length=100)),
                ('api_endpoint', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('modules_used', models.JSONField(default=list)),
                ('answer', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('response_time_ms', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
