# Generated by Django 6.0.6 on 2026-06-17 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMInteractionLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('tools_called', models.JSONField(default=list)),
                ('token_usage', models.IntegerField(default=0)),
                ('response_time', models.FloatField()),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
